language: csharp
sudo: required
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
addons:
  apt:
    packages:
      - libunwind8
mono: none
dotnet: 2.0.0
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - release
    - dev
    - MigrateToNetStandard
    - /^rel\/.*$/
    - /^(.*\/)?ci-.*$/
before_install:
  - chmod +x ./Scripts/build.sh
script:
  - ./Scripts/build.sh