//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLib.ComponentModel.DataAnnotations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataAnnotationsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataAnnotationsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLib.ComponentModel.DataAnnotations.Resources.DataAnnotationsResource", typeof(DataAnnotationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not implement IComparable..
        /// </summary>
        internal static string CompareBaseAttribute_DoesNotImplementIComparable {
            get {
                return ResourceManager.GetString("CompareBaseAttribute_DoesNotImplementIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; cannot be compared..
        /// </summary>
        internal static string CompareBaseAttribute_PropertiesCannotBeCompared {
            get {
                return ResourceManager.GetString("CompareBaseAttribute_PropertiesCannotBeCompared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; type ({1}) and &apos;{2}&apos; type ({3}) must be the same..
        /// </summary>
        internal static string CompareBaseAttribute_TypeMissMatch {
            get {
                return ResourceManager.GetString("CompareBaseAttribute_TypeMissMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a property named {0}..
        /// </summary>
        internal static string CompareBaseAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareBaseAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; do not match..
        /// </summary>
        internal static string EqualsToAttribute_ValidationError {
            get {
                return ResourceManager.GetString("EqualsToAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string GreaterThanAttribute_ValidationError {
            get {
                return ResourceManager.GetString("GreaterThanAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be greater than or equals to &apos;{1}&apos;..
        /// </summary>
        internal static string GreaterThanOrEqualsToAttribute_ValidationError {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualsToAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be less than &apos;{1}&apos;..
        /// </summary>
        internal static string LessThanAttribute_ValidationError {
            get {
                return ResourceManager.GetString("LessThanAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be less than or equals to &apos;{1}&apos;..
        /// </summary>
        internal static string LessThanOrEqualsToAttribute_ValidationError {
            get {
                return ResourceManager.GetString("LessThanOrEqualsToAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and &apos;{1}&apos; must not match..
        /// </summary>
        internal static string NotEqualsToAttribute_ValidationError {
            get {
                return ResourceManager.GetString("NotEqualsToAttribute_ValidationError", resourceCulture);
            }
        }
    }
}
