//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLib.Collections.Generic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GraphResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLib.Collections.Generic.Resources.GraphResource", typeof(GraphResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;compararison&apos;&quot;.
        /// </summary>
        internal static string comparaisonException {
            get {
                return ResourceManager.GetString("comparaisonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;It is not an directed edge.&quot;.
        /// </summary>
        internal static string directedEdgeException {
            get {
                return ResourceManager.GetString("directedEdgeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;x&apos; &quot;.
        /// </summary>
        internal static string equalsLeftArgumentException {
            get {
                return ResourceManager.GetString("equalsLeftArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;y&apos;&quot;.
        /// </summary>
        internal static string equalsRightArgumentException {
            get {
                return ResourceManager.GetString("equalsRightArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;from&apos;&quot;.
        /// </summary>
        internal static string fromArgumentException {
            get {
                return ResourceManager.GetString("fromArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;typeName&apos;&quot;.
        /// </summary>
        internal static string GraphFactoryException {
            get {
                return ResourceManager.GetString("GraphFactoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;obj&apos;&quot;.
        /// </summary>
        internal static string GraphNodeArgumentException {
            get {
                return ResourceManager.GetString("GraphNodeArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;value&apos;&quot;.
        /// </summary>
        internal static string GraphNodeValueException {
            get {
                return ResourceManager.GetString("GraphNodeValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;item&apos;&quot;.
        /// </summary>
        internal static string itemArgumentException {
            get {
                return ResourceManager.GetString("itemArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Require argument &apos;to&apos;&quot;.
        /// </summary>
        internal static string toArgumentException {
            get {
                return ResourceManager.GetString("toArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;It is not an undirected edge.&quot;.
        /// </summary>
        internal static string unDirectedEdgeException {
            get {
                return ResourceManager.GetString("unDirectedEdgeException", resourceCulture);
            }
        }
    }
}
