//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RationalNumberResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RationalNumberResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLib.Resources.RationalNumberResource", typeof(RationalNumberResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The obj must be a RationalNumber or can be implicit converted to RationalNumber.
        /// </summary>
        internal static string CompareTo_InvalidCastException_Obj {
            get {
                return ResourceManager.GetString("CompareTo_InvalidCastException_Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The denominator must be non-zero..
        /// </summary>
        internal static string Initialize_DivideByZeroException_Denominator {
            get {
                return ResourceManager.GetString("Initialize_DivideByZeroException_Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is not well formatted. Expected {0} / {1} or {0} / {1} / {2}.
        /// </summary>
        internal static string RationalNumber_ArgumentException_S {
            get {
                return ResourceManager.GetString("RationalNumber_ArgumentException_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the string to RationalNumber.
        /// </summary>
        internal static string RationalNumber_ArithmeticException {
            get {
                return ResourceManager.GetString("RationalNumber_ArithmeticException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numerator must be non-zero.
        /// </summary>
        internal static string Reverse_DivideByZeroException_R {
            get {
                return ResourceManager.GetString("Reverse_DivideByZeroException_R", resourceCulture);
            }
        }
    }
}
